---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: suvratam/staragileprojectmedicure:v1
          ports:
            - containerPort: 8082          # <-- Corrected to 8082
          env:
            - name: PORT
              value: "8082"                # <-- Corrected to 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicure
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - port: 8082                          # <-- Service port
      targetPort: 8082                    # <-- Must match container port
      nodePort: 32438  
